language: csharp
solution: Freeserf.net.sln
script:
  - nuget restore
  - msbuild /p:Configuration=Release Freeserf.net.sln

stages:
  - name: deploy
    if: branch = master AND type = push AND os = linux

before_deploy:
  - tar -cvzf Freeserf.net-Linux.tar.gz Freeserf.net/bin/Release/Freeserf.net.exe

deploy:
    provider: releases
    api_key:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    file: Freeserf.net-Linux.tar.gz
    skip_cleanup: true
    draft: true
    overwrite: true
    prerelease: false
    name: Freeserf.net-$(TRAVIS_TAG)
    body: Release $(TRAVIS_TAG)
    on:
        tags: true