image: Visual Studio 2017

environment:
  WINDOWS: 1

platform: Any CPU
configuration: Release

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - nuget restore -verbosity detailed
  - msbuild -t:restore

artifacts:
  - path: Freeserf.net.zip
    name: Freeserf.net

after_build:
  - 7z a Freeserf.net.zip %APPVEYOR_BUILD_FOLDER%\Freeserf.net\bin\Release\Freeserf.net.exe