image: Visual Studio 2017

environment:
  WINDOWS: 1

platform: Any CPU
configuration: Release

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - nuget restore -verbosity detailed